services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile.web
      target: runner
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
    depends_on:
      - lenticular
    networks:
      - app-network

  lenticular:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "8081:8081"
    networks:
      - app-network
    restart: always
    command: ["./lenticular"]

networks:
  app-network:
    driver: bridge
